//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalSetting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 安装路径 {
            get {
                return ((string)(this["安装路径"]));
            }
            set {
                this["安装路径"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VRSteam教室\\VRSteam教室")]
        public string VRSteam教室 {
            get {
                return ((string)(this["VRSteam教室"]));
            }
            set {
                this["VRSteam教室"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("串联电路\\串联电路")]
        public string 串联电路 {
            get {
                return ((string)(this["串联电路"]));
            }
            set {
                this["串联电路"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("单摆\\单摆")]
        public string 单摆 {
            get {
                return ((string)(this["单摆"]));
            }
            set {
                this["单摆"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("弹力\\弹力")]
        public string 弹力 {
            get {
                return ((string)(this["弹力"]));
            }
            set {
                this["弹力"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("电磁\\电磁")]
        public string 电磁 {
            get {
                return ((string)(this["电磁"]));
            }
            set {
                this["电磁"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("浮力\\浮力")]
        public string 浮力 {
            get {
                return ((string)(this["浮力"]));
            }
            set {
                this["浮力"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("光合 呼吸作用\\光合和呼吸作用")]
        public string 光合呼吸作用 {
            get {
                return ((string)(this["光合呼吸作用"]));
            }
            set {
                this["光合呼吸作用"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("滑轮组\\滑轮组")]
        public string 滑轮组 {
            get {
                return ((string)(this["滑轮组"]));
            }
            set {
                this["滑轮组"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("化学分子式\\化学分子式")]
        public string 化学分子式 {
            get {
                return ((string)(this["化学分子式"]));
            }
            set {
                this["化学分子式"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("摩擦力\\摩擦力")]
        public string 摩擦力 {
            get {
                return ((string)(this["摩擦力"]));
            }
            set {
                this["摩擦力"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("人体解剖\\人体解剖")]
        public string 人体解剖 {
            get {
                return ((string)(this["人体解剖"]));
            }
            set {
                this["人体解剖"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("拆车\\拆车")]
        public string 拆车 {
            get {
                return ((string)(this["拆车"]));
            }
            set {
                this["拆车"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("磁生电\\磁生电")]
        public string 磁生电 {
            get {
                return ((string)(this["磁生电"]));
            }
            set {
                this["磁生电"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("汉语乐园\\汉语乐园")]
        public string 汉语乐园 {
            get {
                return ((string)(this["汉语乐园"]));
            }
            set {
                this["汉语乐园"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("水果忍者\\水果忍者")]
        public string 水果忍者 {
            get {
                return ((string)(this["水果忍者"]));
            }
            set {
                this["水果忍者"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("太阳系\\太阳系")]
        public string 太阳系 {
            get {
                return ((string)(this["太阳系"]));
            }
            set {
                this["太阳系"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("眼球实验实物识别\\正常人眼\\正常人眼")]
        public string 正常眼 {
            get {
                return ((string)(this["正常眼"]));
            }
            set {
                this["正常眼"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("眼球实验实物识别\\近视眼\\近视眼")]
        public string 近视眼 {
            get {
                return ((string)(this["近视眼"]));
            }
            set {
                this["近视眼"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("眼球实验实物识别\\远视眼\\近视眼")]
        public string 远视眼 {
            get {
                return ((string)(this["远视眼"]));
            }
            set {
                this["远视眼"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("折射实验\\折射物理实验")]
        public string 折射实验 {
            get {
                return ((string)(this["折射实验"]));
            }
            set {
                this["折射实验"] = value;
            }
        }
    }
}
